name: Build and Deploy
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  Dependencies:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3

      - name: Install Dependencies ğŸ”§
        run: npm ci
        
  Test :
    needs: Dependencies
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps: 
      - name: Run Cypress Tests 
        run: npm run cypress:run

  Build:
    needs: Test
    runs-on: ubunu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Build ğŸš§
        run: npm run build
    
  Deploy:
    needs: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3

      - name: Deploy ğŸš€
        if: success() # DÃ©ploie seulement si les Ã©tapes prÃ©cÃ©dentes ont rÃ©ussi.
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build # Le dossier que l'action doit dÃ©ployer
